### PR TITLE
This change builds on Gentoo

### PR DESCRIPTION
**Pull request by eyoung100**
This causes all components to be built on Gentoo, There's still  a problem which I'll open an issue for.

### CODE REVIEW

**Comment by mellinoe** [comment]
Hi @eyoung100 , thanks for the pull request! Could you help me understand how this fixes the build on your platform? Are the build scripts making some assumptions about the current directory that aren't working on your distro? If that's the case, we may be able to fix that sort of thing over in the other repos. Or is the problem that you need to run the build scripts with `sh` rather than `bash`?

**Comment by mellinoe** [comment]
It looks like the build output of core-setup is relative to the current working directory. I'd like to understand a couple things and based on that I have a couple of ideas on how to approach this:
- Is running the scripts in a different working directory a requirement for you? Related to the questions I asked above. Is using `sh` rather than `bash` a requirement? I would expect that `bash` is available on Gentoo, no?
- If we need to execute the individual build scripts in a different directory, I think we should combine the three lines into a single call in a separate shell command such that the overall script's working directory is never changed. That will help mitigate problems with one build script affecting another. Something like 
  `(cd coreclr && exec build.sh $__configuration $__build_arch 2>&1 | tee coreclr.log)` for each of the build commands.
- We might just want to formalize the "copy from core-setup" process like the corefx and coreclr copies are done. They allow you to pass in a `--coreclrbin` or `--corefxbin` path to force copying from a specific place, or they parse the location out of the build script output. Core-setup's build prints something like this, which we could parse in a similar way:

```
Building Corehost from <sourcepath> to <destinationpath>
```

We're interested in `<destinationpath>`.

I would definitely like to understand why the current build script doesn't work on Gentoo, though; please at least clarify that part so I have a better understanding of what we're dealing with.

**Comment by eyoung100** [comment]
1. Using `sh` is not required.    On Gentoo `sh` is symlinked to my current shell, which is `bash`.  I think this is the default behavior for all distributions.  I "cheated" since I was comfortable doing so.
2.  I based my layout on the layout of your repository.  See the screenshot, and yes that is the unity desktop running on Gentoo:
   screenshot from 2016-10-05 19-08-36

Putting all these in the same working directory would help, just from a simplicity standpoint.  Regarding the pathing, I can't explain why breaking it up helps, but if I don't `cd` into the working directory for the core-setup task, I get `Unknown argument 1.0.2`, and core-setup never builds.  I know using the `./` convention is considered overkill, but since I am a perfectionist, I added it to ensure I ended up where needed.  Technically(for some reason only core-setup was failing), I didn't need it for the CORECLR  or COREFX task, but I wanted the sections to look the same, so I added the `cd`'s etc
1. Regarding the copies, I had to add `./core-setup/src/corehost/` when I realized the output from `core-setup` wasn't relative (The `cli` dir is not copied to the bootstrap root after the CMake process).  An automated process would be nice here.
2.  The problem we're facing if we want all these in the same directory is that git doesn't allow cloning items into a non empty directory

**Comment by mellinoe** [comment]
> if I don't cd into the working directory for the core-setup task, I get `Unknown argument 1.0.2`, and core-setup never builds. 

Interesting. I think that this indicates that the parameters aren't getting passed into that other script correctly (that is an error message from the other build script). Could you experiment with adding some extra quotation marks around the script arguments passed into the core-setup build on line 78, without the rest of your changes?

I'd prefer to just make a change like the above instead of doing a bunch of extra stuff like changing directories, etc. if it isn't required. From what you've described, I think the real root problem here is the arguments are getting passed to core-setup's `build.sh` script incorrectly.

**Comment by eyoung100** [comment]
I'll do that shortly, I need to recopy all the pieces, but for now my final working script is in PR #6 .  Have a look

**Comment by eyoung100** [comment]
It's working if the parameters in the build line (78) are double quoted!!! Sorry for polluting your repository...  I'll close all my PR's and submit a new one with the quoted fix

**Pull request closed without merging**
