### PR TITLE
Update buildall.sh

### PR DESCRIPTION
**Pull request by eyoung100**
Fixed Copy Error

### CODE REVIEW

**Comment by mellinoe** [comment]
I believe this is due to the other change made in #3 , which changes the working directory before running the build script. It seems that the build output of core-setup is actually based on your current working directory, rather than as a relative path from the actual core-setup sources. Since this change goes hand-in-hand with the other one, could you add these changes to #3? I have some suggestions on how to approach this, but it would be best to consolidate it over there.

**Comment by eyoung100** [comment]
Can you accept PR #3 #4 and #5 all at once otherwise, do I need to close all these and update as PR #6?  If so, we lose #3

**Comment by mellinoe** [comment]
I actually just meant to combine this with #3 by putting the commit here on top of that branch, since this seems to be addressing a problem introduced by the path-changing in that PR. Make sense?

**Comment by eyoung100** [comment]
I'm not sure I know how to do that without closing all the others... See PR 6

**Comment by eyoung100** [comment]
#3 #4 and #5 . are now combined in #6.  Closing

**Pull request closed without merging**
